# This is a placeholder so actions won't default to a getting started page

name: Python Build Pipeline

on:
  push:
    branches: 
      - main

jobs:
  buildpython:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install libraries
        run: |
            cd function
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
      - name: Create zip bundle
        run: |
            cd function
            zip -r ../${{ github.sha }}.zip .
      - name: upload artifact
        uses: actions/upload-artifact@v3m
        with:
          name: my-artifact
          path: ${{ github.sha }}.zip      
